name: Maven build and Docker publish

on:
  push:
    branches:
    - main

jobs:
  build:
    name: "Build the app"

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        cache: 'maven'
    
    - name: Build with Maven
      run: ./mvnw package 

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:
    name: "Build docker image"
    
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code # Required for the DockerFile
        uses: actions/checkout@v4

      - name: Download artifact from maven job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Logging in to Docker
        run: docker login ghcr.io -u adaz008 -p ${{ github.token }}

      - name: Build the Docker image
        run: docker build . -t ghcr.io/adaz008/cubix/1/homework/app:springboot

      - name: Publishing the Docker image
        run: docker push ghcr.io/adaz008/cubix/1/homework/app:springboot

  verify:
    name: "Verify Docker image"

    runs-on: ubuntu-latest
    needs: docker

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code # Required for the verify-image.sh
        uses: actions/checkout@v4

      - name: Logging in to Docker
        run: docker login ghcr.io -u adaz008 -p ${{ github.token }}

      - name: Pull the Docker image
        run: docker pull ghcr.io/adaz008/cubix/1/homework/app:springboot

      - name: Verify the image
        run: ./verify-image.sh
